### ISSUE TITLE
TypeError: Cannot read property 'groups' of undefined

### ISSUE THREAD

**Issue by cbrwizard** [cbrwizard/squardak#53]
https://sentry.io/squardak/squardak/issues/300060479/

```
TypeError: Cannot read property 'groups' of undefined
  at t.updateSquaresRecords (/app_2300587b993e91ec3aff.js:11:161320)
  at None (/app_2300587b993e91ec3aff.js:35:212715)
  at i (/app_2300587b993e91ec3aff.js:822:483361)
  at Generator._invoke (/app_2300587b993e91ec3aff.js:822:484457)
  at Generator.e.(anonymous function) [as next] (/app_2300587b993e91ec3aff.js:822:483540)
...
(39 additional frame(s) were not displayed)
```

**Comment by cbrwizard** [comment]
This happens when the player went to the game and the game manipulation functions are already running because of the finished turns but the Phaser isn't yet initialized

**Comment by cbrwizard** [comment]
https://sentry.io/squardak/squardak/issues/300032898/

**Comment by cbrwizard** [comment]
Done
