### ISSUE TITLE
422: Unprocessable Entity

### ISSUE THREAD

**Issue by cbrwizard** [cbrwizard/squardak#56]
https://sentry.io/squardak/squardak/issues/300053256/

```
422: Unprocessable Entity
  at i (/app_2300587b993e91ec3aff.js:11:76483)
  at None (/app_2300587b993e91ec3aff.js:11:77149)
```

**Comment by cbrwizard** [comment]
https://yadi.sk/i/75_-Zctr3KPbL9
app_2300587b993e91ec3aff.js:822 POST http://squardak.xyz:3000/games 422 (Unprocessable Entity)
(anonymous) @ app_2300587b993e91ec3aff.js:822
t.fetchUrl @ app_2300587b993e91ec3aff.js:11
t.fetchJSON @ app_2300587b993e91ec3aff.js:11
t.postStart @ app_2300587b993e91ec3aff.js:28
M @ app_2300587b993e91ec3aff.js:35
x @ app_2300587b993e91ec3aff.js:35
y @ app_2300587b993e91ec3aff.js:35
s @ app_2300587b993e91ec3aff.js:35
C @ app_2300587b993e91ec3aff.js:35
x @ app_2300587b993e91ec3aff.js:35
y @ app_2300587b993e91ec3aff.js:35
n @ app_2300587b993e91ec3aff.js:35
E @ app_2300587b993e91ec3aff.js:35
x @ app_2300587b993e91ec3aff.js:35
y @ app_2300587b993e91ec3aff.js:35
n @ app_2300587b993e91ec3aff.js:35
s @ app_2300587b993e91ec3aff.js:35
t @ app_2300587b993e91ec3aff.js:11
(anonymous) @ app_2300587b993e91ec3aff.js:11
(anonymous) @ app_2300587b993e91ec3aff.js:11
n @ app_2300587b993e91ec3aff.js:35
s @ app_2300587b993e91ec3aff.js:35
i @ app_2300587b993e91ec3aff.js:35
(anonymous) @ app_2300587b993e91ec3aff.js:11
t @ app_2300587b993e91ec3aff.js:11
(anonymous) @ app_2300587b993e91ec3aff.js:822
onGuestSubmit @ app_2300587b993e91ec3aff.js:35
b @ app_2300587b993e91ec3aff.js:822
s @ app_2300587b993e91ec3aff.js:822
value @ app_2300587b993e91ec3aff.js:822
n @ app_2300587b993e91ec3aff.js:14
o @ app_2300587b993e91ec3aff.js:11
s @ app_2300587b993e91ec3aff.js:11
p @ app_2300587b993e91ec3aff.js:11
m @ app_2300587b993e91ec3aff.js:11
n @ app_2300587b993e91ec3aff.js:35
processEventQueue @ app_2300587b993e91ec3aff.js:11
n @ app_2300587b993e91ec3aff.js:822
handleTopLevel @ app_2300587b993e91ec3aff.js:822
r @ app_2300587b993e91ec3aff.js:822
perform @ app_2300587b993e91ec3aff.js:11
batchedUpdates @ app_2300587b993e91ec3aff.js:822
r @ app_2300587b993e91ec3aff.js:11
dispatchEvent @ app_2300587b993e91ec3aff.js:822
n @ app_2300587b993e91ec3aff.js:822

**Comment by cbrwizard** [comment]
Mac opera, chrome

**Comment by cbrwizard** [comment]
A theory is that it happens because a non-unique nick is generated. I need to test that. If it's true, then I need to improve the error message and add a UUID to a generated nick.

**Comment by cbrwizard** [comment]
Done
