### ISSUE TITLE
TypeError: Object doesn't support property or method 'closest'

### ISSUE THREAD

**Issue by cbrwizard** [cbrwizard/squardak#88]
https://sentry.io/squardak/squardak/issues/304832486/

```
TypeError: Object doesn't support property or method 'closest'
  at c (/app_2300587b993e91ec3aff.js:11:135985)
  at s (/app_2300587b993e91ec3aff.js:11:135271)
  at n (/app_2300587b993e91ec3aff.js:822:140651)
```

**Comment by cbrwizard** [comment]
Bummer, happened again
